name: Helm Release Workflow

on:
  workflow_call:
    inputs:
      gh_repository_owner:
        required: true
        type: string
      gh_event_name:
        required: true
        type: string
      gh_ref:
        required: true
        type: string
      gh_handle:
        required: true
        type: string
      chart:
        required: true
        type: string
      chart_version:
        required: true
        type: string
      image_repository:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      image_digest:
        required: true
        type: string
      GPG_KEYRING_BASE64:
        required: true
        type: string
      GPG_PASSPHRASE:
        required: true
        type: string
      GPG_KEY:
        required: true
        type: string
      gh_token:
        required: true
        type: string
      
jobs:
  helm:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: ${{ inputs.gh_repository_owner == 'ortelius' && inputs.gh_event_name == 'push' && inputs.gh_ref == 'refs/heads/main' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Helm Chart Releaser
        uses: ortelius/ms-cr-action@d98a4163765db41dbc8159f3a31f30f77bbe23bd # v1.2.0
        with:
          gpg_keyring_base64: ${{ inputs.GPG_KEYRING_BASE64 }}
          gpg_passphrase: ${{ inputs.GPG_PASSPHRASE }}
          gpg_key: ${{ inputs.GPG_KEY }}
          gh_token: ${{ inputs.gh_token }}
          gh_handle: ${{ inputs.gh_handle }}
          chart: ${{ inputs.chart }}
          chart_version: ${{ inputs.chart_version }}
          image_repository: ${{ inputs.image_repository }}
          image_tag: ${{ inputs.image_tag }}
          image_digest: ${{ inputs.image_digest }}

      - name: Trigger Rebuild of Main Chart
        uses: benc-uk/workflow-dispatch@798e70c97009500150087d30d9f11c5444830385 # v1.2.2
        with:
          workflow: generate-main-chart.yml
          repo: ortelius/ortelius-charts
          token: ${{ inputs.gh_token }}